public enum WhalepassApiEndpoint
{
    ENROLL,
    UPDATE_EXP,
    COMPLETE_ACTION,
    COMPLETE_CHALLENGE,
    GET_PLAYER_INVENTORY,
    GET_PLAYER_PROGRESS_BASE,
    GET_REDIRECTION_LINK,
    GET_BATTLEPASS,
    GET_BATTLEPASS_BASE
}
